full_name: JAYANT NAGLE
languages: [en, hn]
profile_photo: true
profile_picture_path: img/profile.jpeg
contact:
  website: https://nodexploit.com
  email: jayantna@live.com
  linkedin: https://www.linkedin.com/in/jayantn/
  github:
  stack_overflow:
  google_analytics:
